from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc




class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(807, 557)
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.bus = QtWidgets.QPushButton(self.centralwidget)
        self.bus.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.bus.setObjectName("bus")
        self.ticket = QtWidgets.QPushButton(self.centralwidget)
        self.ticket.setGeometry(QtCore.QRect(80, 0, 75, 23))
        self.ticket.setObjectName("ticket")
        self.buyticket = QtWidgets.QPushButton(self.centralwidget)
        self.buyticket.setGeometry(QtCore.QRect(160, 0, 91, 23))
        self.buyticket.setObjectName("buyticket")
        self.driver = QtWidgets.QPushButton(self.centralwidget)
        self.driver.setGeometry(QtCore.QRect(260, 0, 75, 23))
        self.driver.setObjectName("driver")
        self.number = QtWidgets.QComboBox(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(430, 0, 281, 22))
        self.number.setObjectName("number")
        self.number.addItem("")
        self.number.addItem("")
        self.number.addItem("")
        self.number.addItem("")
        self.routetable = QtWidgets.QTableWidget(self.centralwidget)
        self.routetable.setGeometry(QtCore.QRect(10, 30, 791, 481))
        self.routetable.setObjectName("routetable")
        self.routetable.setColumnCount(10)
        self.routetable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.routetable.setHorizontalHeaderItem(9, item)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(-10, -10, 811, 41))
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.search = QtWidgets.QPushButton(self.groupBox)
        self.search.setGeometry(QtCore.QRect(730, 10, 75, 23))
        self.search.setObjectName("search")
        self.groupBox.raise_()
        self.bus.raise_()
        self.ticket.raise_()
        self.buyticket.raise_()
        self.driver.raise_()
        self.number.raise_()
        self.routetable.raise_()
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(main)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

        connection = pyodbc.connect('Driver={SQL Server};' 'Server=VLADPC;' 'Database=bus_station_database_04_04_2022;' 'Trusted_connection=yes;')
        cursor = connection.cursor()
        cursor.execute('SELECT * FROM route')
        self.routetable.setRowCount(0)
        for row_number, row_data in enumerate(cursor):
            self.routetable.insertRow(row_number)
            for colum_number, data in enumerate(row_data):
                self.routetable.setItem(row_number, colum_number, QtWidgets.QTableWidgetItem(str(data)))
        connection.commit()

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Автовокзальная касса"))
        self.bus.setText(_translate("main", "Автобусы"))
        self.ticket.setText(_translate("main", "Билеты"))
        self.buyticket.setText(_translate("main", "Продать билет"))
        self.driver.setText(_translate("main", "Водители"))
        self.number.setItemText(0, _translate("main", "Сортировка по номеру"))
        self.number.setItemText(1, _translate("main", "22"))
        self.number.setItemText(2, _translate("main", "33"))
        self.number.setItemText(3, _translate("main", "47"))
        item = self.routetable.horizontalHeaderItem(0)
        item.setText(_translate("main", "Id"))
        item = self.routetable.horizontalHeaderItem(1)
        item.setText(_translate("main", "Пункт оправления"))
        item = self.routetable.horizontalHeaderItem(2)
        item.setText(_translate("main", "Пункт прибытия"))
        item = self.routetable.horizontalHeaderItem(3)
        item.setText(_translate("main", "Id Автобуса"))
        item = self.routetable.horizontalHeaderItem(4)
        item.setText(_translate("main", "Id Водителя"))
        item = self.routetable.horizontalHeaderItem(5)
        item.setText(_translate("main", "Время отправления"))
        item = self.routetable.horizontalHeaderItem(6)
        item.setText(_translate("main", "Время прибытия"))
        item = self.routetable.horizontalHeaderItem(7)
        item.setText(_translate("main", "Свободных мест"))
        item = self.routetable.horizontalHeaderItem(8)
        item.setText(_translate("main", "Номер маршрута"))
        item = self.routetable.horizontalHeaderItem(9)
        item.setText(_translate("main", "Цена"))
        self.search.setText(_translate("main", "Поиск"))
        self.menu.setTitle(_translate("main", "Файл"))
        self.menu_2.setTitle(_translate("main", "О программе"))
        self.action.setText(_translate("main", "Выйти"))


